version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  nextjs:
    build:
      context: ./nextapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CUSTOM_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped